version: "3"
services:
  api:
    image: ./buisnes/api:v1.2
    build: 
      context: api
      dockerfile: ../api.Dockerfile
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo
    ports:
      - "3000:3000"
    networks:
      - app7
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - "9091:27017"
    volumes:
      - database:/data/db
    networks:
      - app7
volumes:
  database:
networks:
  app7:
